name: prayer_time_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase相关依赖
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  
  # 权限和UI相关依赖
  permission_handler: ^10.4.3
  flutter_svg: ^2.0.7
  geolocator: ^10.0.1
  qibla_direction: ^1.0.1
  sensors_plus: ^4.0.2
  image_picker: ^1.0.4
  
  # 工具库依赖
  intl: ^0.18.1
  geocoding: ^2.1.1
  http: ^1.1.0
  adhan: ^2.0.0+1
  
  # 通知相关依赖 - 只使用一个
  flutter_local_notifications: ^15.1.0+1
  # awesome_notifications: ^0.7.4+1  # 注释掉，避免冲突
  
  # 伊斯兰教相关依赖
  flutter_islamic_icons: ^1.0.2
  hijri: ^3.0.0
  islamic_hijri_calendar: ^0.0.4
  
  # 其他功能性依赖
  isar: ^3.1.0+1
  flutter_compass: ^0.8.0
  url_launcher: ^6.1.14
  provider: ^6.0.5
  table_calendar: ^3.0.9
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  shared_preferences: ^2.2.1
  quran: ^1.2.2
  google_fonts: ^5.1.0
  fl_chart: ^0.63.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/compass.png
    - assets/images/needle.png
    - assets/images/qiblah.png
    - assets/images/mosque.jpg